### ISSUE TITLE
a error 

### ISSUE THREAD

**Issue by chenyinhuan** [CherryProjects/rbac#21]
when use 'const rbac = new RBAC({
      roles: ['admin', 'user']  
    }, (err, rbac) => {
      if (err) throw err;
      // setup express routes
      app.use('/admin', secure.hasRole(rbac, 'admin'), adminController);
    });' 
return a reeor 'RBAC is not a constructor'?

**Comment by seeden** [comment]
// ES6 import RBAC from 'rbac';
// ES5 var RBAC = require('rbac').default;
